name: Verify

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: 7.3
          coverage: pcov

      - name: Install dependencies
        run: composer install
        
      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-text

  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: 7.3
          coverage: none
          tools: cs2pr

      - name: Install dependencies
        run: composer install

      - name: Run PHP Codesniffer
        run: vendor/bin/phpcs --report=checkstyle -q | cs2pr --graceful-warnings

  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: 7.3
          coverage: none
          tools: cs2pr

      - name: Install dependencies
        run: composer install
        
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr
